# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

"""Apply the converter's OWN output to a live Aurora DSQL cluster and report rejections.

Why this exists
---------------
The unit tests assert on the generated DDL **text**, so they can only catch what someone
thought to write down. Nothing ever asked DSQL whether that text is legal -- and a
snapshot test will happily pin DDL the cluster refuses. Three real defects hid in exactly
that blind spot:

* ``GENERATED BY DEFAULT AS IDENTITY (CACHE 100)`` -- DSQL accepts only ``CACHE = 1`` or
  ``CACHE >= 65536``, so every identity-strategy table failed to apply.
* an ``INT`` identity column -- DSQL sequences are BIGINT-only, and MySQL
  ``int AUTO_INCREMENT`` is the most common primary key there is.
* ``DECIMAL(65,30)`` -- MySQL's maximum, past DSQL's ``(38,37)`` ceiling.

The end-to-end run did not catch them either, because it exercises one hand-built schema
that happens to contain none of those shapes.

What it does
------------
Two sweeps, both against a scratch schema that is dropped afterwards:

1. ``--source-schema``: reflect every table in a real MySQL schema, convert it, and apply
   the result (table DDL + index DDL) to DSQL. This is the "does MY database convert?"
   check an operator can run before a migration.
2. the built-in synthetic matrix: one table per MySQL type/attribute/default form,
   including the long tail a given schema will not contain (SET, BIT, spatial, wide
   DECIMAL, quoted defaults, ...). This is the regression net for the converter itself.

Every primary-key strategy is exercised, since two of the three defects were only
reachable through the identity path.

Read-only against the SOURCE (reflection only). On the TARGET it creates and drops
tables in a scratch schema (default ``dsql_conversion_verify``) and touches nothing else.

Usage
-----
    .venv/bin/python scripts/verify_conversion_on_dsql.py                  # synthetic only
    .venv/bin/python scripts/verify_conversion_on_dsql.py --source-schema ecommerce_demo
    .venv/bin/python scripts/verify_conversion_on_dsql.py --all-schemas

Reads ``.env`` for DB_HOST/DB_PORT/DB_USER/DB_PASSWORD (source) and
TARGET_ENDPOINT/TARGET_REGION/TARGET_DATABASE/TARGET_USERNAME (target). Exits non-zero
when anything was rejected, so it can gate a release.
"""

from __future__ import annotations

import argparse
import os
import sys
from dataclasses import dataclass
from typing import Optional

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src"))

from _common import load_dotenv, log, validate_identifier  # noqa: E402

from dsql_migrator.config import SecretValue  # noqa: E402
from dsql_migrator.core.converter import (  # noqa: E402
    PrimaryKeyStrategy,
    SchemaConverter,
    SchemaConvertOptions,
)
from dsql_migrator.core.models import (  # noqa: E402
    ColumnDef,
    TableDef,
    TargetConnectionConfig,
)
from dsql_migrator.core.target_connection import DsqlConnector  # noqa: E402

DEFAULT_SCRATCH = "dsql_conversion_verify"

# One table per MySQL shape worth proving, chosen to cover what a single real schema
# will NOT contain. ``(label, mysql_type, column_kwargs)``.
SYNTHETIC_CASES: tuple[tuple[str, str, dict], ...] = (
    # Integer family (incl. the unsigned widening rules).
    ("tinyint", "tinyint", {}),
    ("tinyint unsigned", "tinyint unsigned", {}),
    ("smallint unsigned", "smallint unsigned", {}),
    ("mediumint", "mediumint", {}),
    ("int unsigned", "int unsigned", {}),
    ("bigint unsigned", "bigint unsigned", {}),
    ("int zerofill", "int(5) zerofill", {}),
    # Approximate + exact numerics, including MySQL's maximum DECIMAL.
    ("float", "float", {}),
    ("float(10,2)", "float(10,2)", {}),
    ("double", "double", {}),
    ("decimal(10,2)", "decimal(10,2)", {}),
    ("decimal max (65,30)", "decimal(65,30)", {}),
    ("decimal(38,37)", "decimal(38,37)", {}),
    ("decimal unsigned", "decimal(12,4) unsigned", {}),
    # Temporal.
    ("date", "date", {}),
    ("time", "time", {}),
    ("year", "year", {}),
    ("datetime", "datetime", {}),
    ("datetime(6)", "datetime(6)", {}),
    ("timestamp", "timestamp", {}),
    # Character + binary.
    ("char(255)", "char(255)", {}),
    ("varchar(21000)", "varchar(21000)", {}),
    ("tinytext", "tinytext", {}),
    ("text", "text", {}),
    ("mediumtext", "mediumtext", {}),
    ("longtext", "longtext", {}),
    ("binary(16)", "binary(16)", {}),
    ("varbinary(255)", "varbinary(255)", {}),
    ("blob", "blob", {}),
    ("longblob", "longblob", {}),
    ("bit(8)", "bit(8)", {}),
    # Structured / MySQL-only.
    ("json", "json", {}),
    ("enum", "enum('a','b','c')", {}),
    ("set", "set('a','b')", {}),
    ("geometry", "geometry", {}),
    ("point", "point", {}),
    # DEFAULT forms. These use the ENRICHED shape -- an UNQUOTED value from
    # information_schema.COLUMN_DEFAULT, with an expression marked by
    # default_is_expression (EXTRA's DEFAULT_GENERATED) -- because that is the only
    # input the converter supports. Writing them in the raw SQLAlchemy-reflected shape
    # instead would test a code path the app never takes.
    ("default int", "int", {"default": "0"}),
    ("default negative", "int", {"default": "-1"}),
    ("default text", "varchar(20)", {"default": "hi"}),
    ("default empty string", "varchar(10)", {"default": ""}),
    ("default quote in text", "varchar(20)", {"default": "it's"}),
    ("default decimal", "decimal(10,2)", {"default": "1.50"}),
    ("default enum", "enum('a','b')", {"default": "a"}),
    ("default bool true", "tinyint(1)", {"default": "1"}),
    ("default bool false", "tinyint(1)", {"default": "0"}),
    ("default tinyint1 unsigned", "tinyint(1) unsigned", {"default": "1"}),
    (
        "default current_timestamp",
        "datetime",
        {"default": "CURRENT_TIMESTAMP", "default_is_expression": True},
    ),
    (
        "default timestamp tz",
        "timestamp",
        {"default": "CURRENT_TIMESTAMP", "default_is_expression": True},
    ),
    ("default + NOT NULL", "int", {"default": "0", "nullable": False}),
    (
        "default translated uuid",
        "char(36)",
        {"default": "uuid()", "default_is_expression": True},
    ),
    (
        "default untranslatable expr",
        "int",
        {"default": "(`id` + 1)", "default_is_expression": True},
    ),
    (
        "default ON UPDATE folded in",
        "datetime",
        {
            "default": "CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP",
            "default_is_expression": True,
        },
    ),
    ("generated column", "int", {"generated": True}),
)

STRATEGIES: tuple[tuple[str, Optional[SchemaConvertOptions]], ...] = (
    ("default", None),
    (
        "identity",
        SchemaConvertOptions(primary_key_strategy=PrimaryKeyStrategy.IDENTITY_WITH_CACHE),
    ),
)


@dataclass
class Failure:
    """One rejected statement, with enough context to act on it."""

    strategy: str
    subject: str
    stage: str  # CONVERT | TABLE | INDEX
    message: str
    ddl: str = ""


def _cfg(env: dict, key: str, default: str = "") -> str:
    """Environment wins over ``.env`` (matches the other scripts' precedence)."""
    return (os.environ.get(key) or env.get(key) or default).strip()


def _target_connection(env: dict):
    endpoint = _cfg(env, "TARGET_ENDPOINT")
    region = _cfg(env, "TARGET_REGION")
    if not endpoint or not region:
        raise SystemExit(
            "error: TARGET_ENDPOINT and TARGET_REGION are required (set them in .env)."
        )
    config = TargetConnectionConfig(
        cluster_endpoint=endpoint,
        region=region,
        database=_cfg(env, "TARGET_DATABASE", "postgres"),
        username=_cfg(env, "TARGET_USERNAME", "admin"),
    )
    connection = DsqlConnector(config).connect()
    connection.autocommit = True
    return connection


def _reflect_source_tables(env: dict, schema: str) -> list[TableDef]:
    """Reflect a real MySQL schema with the tool's own introspection helper."""
    import sqlalchemy

    from dsql_migrator.core.introspector import _reflect_tables, enrich_columns

    password = _cfg(env, "DB_PASSWORD")
    url = sqlalchemy.engine.URL.create(
        "mysql+pymysql",
        username=_cfg(env, "DB_USER"),
        password=password or None,
        host=_cfg(env, "DB_HOST"),
        port=int(_cfg(env, "DB_PORT", "3306") or 3306),
    )
    engine = sqlalchemy.create_engine(url)
    try:
        tables = _reflect_tables(sqlalchemy.inspect(engine), schema=schema)
        # The enrichment pass is NOT optional: it is where information_schema overrides
        # the lossy reflected values (COLUMN_TYPE restores `unsigned`/`tinyint(1)`,
        # COLUMN_DEFAULT replaces the regex-scraped default). Skipping it made this
        # script test a code path the app never uses -- and it duly reported a
        # double-quoting failure that only existed in the un-enriched inventory.
        with engine.connect() as connection:
            enrich_columns(connection, schema, tables)
        return tables
    finally:
        engine.dispose()


def _source_schemas(env: dict) -> list[str]:
    """Every user schema on the source (for ``--all-schemas``)."""
    import sqlalchemy

    url = sqlalchemy.engine.URL.create(
        "mysql+pymysql",
        username=_cfg(env, "DB_USER"),
        password=_cfg(env, "DB_PASSWORD") or None,
        host=_cfg(env, "DB_HOST"),
        port=int(_cfg(env, "DB_PORT", "3306") or 3306),
    )
    engine = sqlalchemy.create_engine(url)
    try:
        with engine.connect() as connection:
            rows = connection.execute(
                sqlalchemy.text(
                    "SELECT SCHEMA_NAME FROM information_schema.SCHEMATA "
                    "WHERE SCHEMA_NAME NOT IN "
                    "('mysql','information_schema','performance_schema','sys')"
                )
            ).all()
        return [row[0] for row in rows]
    finally:
        engine.dispose()


def _synthetic_tables(scratch: str) -> list[TableDef]:
    """One two-column table per synthetic case (BIGINT key + the column under test)."""
    tables: list[TableDef] = []
    for index, (label, mysql_type, kwargs) in enumerate(SYNTHETIC_CASES):
        tables.append(
            TableDef(
                name=f"{scratch}.syn_{index}",
                columns=[
                    ColumnDef(name="id", mysql_type="bigint", nullable=False),
                    ColumnDef(name="c", mysql_type=mysql_type, **kwargs),
                ],
                primary_key=["id"],
                # Exercise the identity path on the key, which is where two of the
                # three known defects lived.
                auto_increment_column="id",
            )
        )
        tables[-1].__dict__["_label"] = label  # for reporting only
    return tables


def _apply(connection, ddls: list[str], scratch: str) -> Optional[tuple[str, str]]:
    """Apply each statement; return ``(stage, message)`` for the first rejection."""
    for ddl in ddls:
        stage = "INDEX" if ddl.strip().upper().startswith("CREATE") and "INDEX" in ddl.upper()[:40] else "TABLE"
        try:
            with connection.cursor() as cursor:
                cursor.execute(ddl)
        except Exception as exc:  # noqa: BLE001 - the whole point is to report it
            return stage, str(exc).strip().splitlines()[0]
    return None


def _sweep(connection, tables: list[TableDef], scratch: str, label: str) -> list[Failure]:
    """Convert + apply every table under every strategy; collect the rejections."""
    failures: list[Failure] = []
    for strategy_name, options in STRATEGIES:
        applied = 0
        for table in tables:
            subject = getattr(table, "_label", None) or table.name
            scratch_table = table.model_copy(
                update={"name": f"{scratch}.{table.name.split('.')[-1]}"}
            )
            try:
                conversion = SchemaConverter().convert_table(scratch_table, options)
            except Exception as exc:  # noqa: BLE001
                failures.append(
                    Failure(strategy_name, str(subject), "CONVERT",
                            str(exc).strip().splitlines()[0])
                )
                continue
            ddls = [conversion.target_ddl, *conversion.index_ddls]
            outcome = _apply(connection, ddls, scratch)
            if outcome is None:
                applied += 1
            else:
                stage, message = outcome
                failures.append(
                    Failure(strategy_name, str(subject), stage, message,
                            conversion.target_ddl)
                )
            # Interpolated into DROP TABLE (identifiers cannot be bound) and derived
            # from a reflected source table name, so validate before it reaches SQL.
            bare = validate_identifier(scratch_table.name.split(".")[-1], "table")
            with connection.cursor() as cursor:
                cursor.execute(f'DROP TABLE IF EXISTS "{scratch}"."{bare}"')
        log(f"  [{label}/{strategy_name}] applied {applied}/{len(tables)}")
    return failures


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Apply converted DDL to a live Aurora DSQL cluster and report "
                    "anything it rejects."
    )
    parser.add_argument(
        "--source-schema", action="append", default=[],
        help="MySQL schema to reflect and convert (repeatable).",
    )
    parser.add_argument(
        "--all-schemas", action="store_true",
        help="Reflect and convert every user schema on the source.",
    )
    parser.add_argument(
        "--no-synthetic", action="store_true",
        help="Skip the built-in synthetic type/default matrix.",
    )
    parser.add_argument("--scratch-schema", default=DEFAULT_SCRATCH)
    args = parser.parse_args()

    env = load_dotenv(".env")
    connection = _target_connection(env)
    # The scratch schema name is interpolated into DROP/CREATE SCHEMA below (an
    # identifier cannot be bound), so a --scratch-schema value is only ever allowed
    # through as a plain identifier -- validate it at the boundary, once.
    scratch = validate_identifier(args.scratch_schema, "scratch schema")

    log(f"scratch schema on the target: {scratch} (dropped at the end)")
    with connection.cursor() as cursor:
        cursor.execute(f'DROP SCHEMA IF EXISTS "{scratch}" CASCADE')
        cursor.execute(f'CREATE SCHEMA "{scratch}"')

    failures: list[Failure] = []
    try:
        if not args.no_synthetic:
            cases = _synthetic_tables(scratch)
            log(f"synthetic matrix: {len(cases)} cases")
            failures += _sweep(connection, cases, scratch, "synthetic")

        schemas = list(args.source_schema)
        if args.all_schemas:
            schemas = _source_schemas(env)
        for schema in schemas:
            tables = _reflect_source_tables(env, schema)
            log(f"source schema {schema}: {len(tables)} tables")
            failures += _sweep(connection, tables, scratch, schema)
    finally:
        with connection.cursor() as cursor:
            cursor.execute(f'DROP SCHEMA IF EXISTS "{scratch}" CASCADE')

    print()
    if not failures:
        log("PASS - every converted statement was accepted by Aurora DSQL")
        return 0

    log(f"FAIL - Aurora DSQL rejected {len(failures)} statement(s):")
    for failure in failures:
        print(f"  [{failure.strategy}] {failure.subject} ({failure.stage})")
        print(f"      {failure.message}")
        if failure.ddl:
            for line in failure.ddl.splitlines():
                print(f"      | {line}")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
